### PR TITLE
Add setting to allow auto close after resizing with keyboard shortcut

### PR DESCRIPTION
**Pull request by mchristiansen**
New setting added as discussed in issue #248

### CODE REVIEW

**Comment by scherepanov** [comment]
Great!
Works as expected.
Merging...

**Comment by pguelpa** [comment]
Was this option dropped at some point? It doesn't seem to be available on version 62

**Comment by schnz** [comment]
It's still available:
image

**Comment by pguelpa** [comment]
Interesting. I have turned this option on, but gTile doesn't close after confirming an operation via keyboard shortcuts.

Maybe I'm thinking of this process incorrectly for how it's supposed to be used? What I'm doing is:

1. Activate gTile
2. Hit "f", my shortcut for resize preset 1 (full screen) and the window resizes
3. gTile UI remains open, here I'm expecting it to close due to me confirming an action. Instead, I have to hit Esc to close it.

Currently on Fedora 42 and gTile 62 (but was on Fedora 41 with the same behavior).

**Comment by schnz** [comment]
The UI stays open when using a preset-shortcut. Otherwise you wouldn't be able to rotate between the preset options when pressing the shortcut multiple times.

The option I referred to in the screenshot does only apply when you are using the arrow keys to move/resize the focused window and confirm the new location/size via <kbd>Enter</kbd>

**Pull request merged**
