### PR TITLE
Fix bugs related to stale monitors variable.

### LINKED ISSUE #57: Montitor hot plug-in not supported
Hello, 
looks like I'm facing the same issue as the clsoed one #42 (waiting to be reopened)
I'm running Gnome 3.30 on Arch

I have a 3-screens setup : laptop + 2 screens over display port.

Only windows on one of them can be tiled using gTile. It's not even the 'main' monito that works.

On others, I get this message when in debug :

`JS ERROR: TypeError: monitor is undefined`

Let me know whatever addition logs I can provide, maybe I can run some additional commands to get info from my monitor setups as seen from gnome ?

### PR DESCRIPTION
**Pull request by gonzojive**
Fix bugs related to stale monitors variable.

This pull request depends on https://github.com/gTile/gTile/pull/143

I believe this fixes #57, though
verification is needed to be sure.

### CODE REVIEW

**Comment by scherepanov** [comment]
Thanks for working on it!
I will test your changes tomorrow night, and will merge into master.
Do I understand it correctly - I need to merge into master merge #142, then #143, and this one #144?

**Comment by gonzojive** [comment]
To test all three changes, you can just clone the hot-plug-monitors branch (the branch associated with this pull request). For ease of review I split the changes into three.

**Comment by scherepanov** [comment]
[sergey@supermedia gTile]$ git status
On branch hot-plug-monitors
nothing to commit, working tree clean
[sergey@supermedia gTile]$ rpm -qa|grep bazel
bazel3-3.4.1-1.fc32.x86_64
[sergey@supermedia gTile]$ bazel run :install-extension
Starting local Bazel server and connecting to it...
INFO: Repository npm instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule yarn_install defined at:
  /home/sergey/.cache/bazel/_bazel_sergey/b40b5bfd955df69f91046dd44feacaf4/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:411:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Not a regular file: /home/sergey/github/gTile/yarn.lock
ERROR: no such package '@npm//@bazel/karma': Not a regular file: /home/sergey/github/gTile/yarn.lock
INFO: Elapsed time: 1.691s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
[sergey@supermedia gTile]$ 

What I am missing?

**Comment by scherepanov** [comment]
For some reason, I had to create yarn.lock
touch /home/sergey/github/gTile/yarn.lock
Then, I was able to install npm and add dependency to karma.
Not sure why I had to create lock file manually.
New version of gTile got installed.
What I can immediately see, gTile window has wrong background. On black background of terminal I can see only letters on title and on buttons. I cannot see selection of tiles on gTile window, and on full screen.
Resize functionality seems to be working fine, hard to check.

**Comment by scherepanov** [comment]
It appears, after install stylesheet.css and images dir are missing.
After manually copying, gTile works properly.
Can you submit one more commit, adding missing files and directory?
Also, I think LICENSE file should be in install...
Apart from this, looks very good.
Can you comment why I have to manually create file yarn.lock?

**Comment by gonzojive** [comment]
yarn.lock should be committed.

Thanks for tracking down the stylesheet and images issue. I don't use the UI so didn't catch that problem. Please try with the new changes.

**Comment by scherepanov** [comment]
Looks good, build/installs without problems.
Testing is fine, have not found any problems.
Merging into master.

**Comment by scherepanov** [comment]
Everything looks very good... thank you very much.
I cannot really test multi-monitor support. I have only single monitor at home, and it is not known when I will be able to come to office where I have multimonitor setup.
I tried to add generation of zip file gTile@vibou.shell-extension.zip to BUILD.bazel:

genrule(
  name = "gen_zip",
  srcs = [":dist_files"],
  tools = ["@bazel_tools//tools/zip:zipper"],
  outs = ["gTile@vibou.shell-extension.zip"],
  cmd = "$(location @bazel_tools//tools/zip:zipper) c $@ $(SRCS)",
)

but it currently exceeding my zero knowledge of bazel.
Can you add generation of zip file for uploading to EGO? It is same as pkg-tar, except it is zip, and output file name is gTile@vibou.shell-extension.zip 

Also, I saw you added some functionality to gTile. Would be very interesting to see it commited to master.

**Comment by scherepanov** [comment]
I look on generated Javascript.
extension.js is humongous 500KB+, because it has some strange huge line commented out at the end.
If I remove this line, size of extension.js goes down to 73KB.
Can you remove this line?
It appears to be a garbage.

**Comment by scherepanov** [comment]
It appears, generated extension.js has appended base64 encoded text of extension.
That is clearly a garbage.
I tried to find why it happens, but it exceed my very low level of bazel knowledge.

**Comment by gonzojive** [comment]
I think the generated base64 at the end is a sourcemap that maps the
generated code line numbers to source code line number. I don't think gjs
has support for this. I'm not sure which step in the compilation process
adds the source map.

**Comment by scherepanov** [comment]
OK, I will investigate

**Comment by gonzojive** [comment]
To zip, you will want to do something along the lines of the answer in
https://stackoverflow.com/questions/57914937/how-do-i-zip-files-in-bazel that
mentions pkg_zip. There is already a pkg_tar rule. You can probably just
copy that rule to something like below (per
https://github.com/bazelbuild/rules_pkg/tree/master/pkg). Alternatively,
modify the install-extension.sh script to zip the output directory.

load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar", "pkg_zip")
pkg_zip(
    name = "dist",
    srcs = [":dist_files"],
)

**Comment by scherepanov** [comment]
Thanks, I got zip working.
For removing source code in base64 encoding from end of extension.js, it appears to be compilerOptions in tsconfig.json - inlineSources and inlineSourceMap. Unfortunately, rule ts_library ignoring them and forced to true. There is another rule ts_project, which has attribute to suppress source map, but I cannot make it working.
Seems to be, easier just remove last line using shell cmd rule.

**Pull request merged**
