### PR TITLE
V28, fix #40, fix #37, fix #32

### LINKED ISSUE #32: Add shortcut for AutoTile
Hi, thanks for the great extension!

I would really like to use a keyboard shortcut for the AutoTile feature, is that possible or does it already exist?

Thanks!

### LINKED ISSUE #37: Hide gtile icon indicator from application bar
Rly do not need it there, how to remove?

thx for awesome extension

### LINKED ISSUE #40: Maximum margin
This is awesome :) But I'd like to use a bigger margin than the currently allowed max of 100px. Eg I run a conky on the edge of my second monitor - I'd like to keep it visible and tile within the remaining area - so I'd like to set eg 'Insets secondary left' to 240px.

### PR DESCRIPTION
**Pull request by scherepanov**
Please look and approve pull request

### CODE REVIEW

**Comment by StuntsPT** [comment]
Looks great.
Code change is easy to follow. I have installed this version from your branch and everything works as expected. Thank you for your efforts! They are appreciated.

**Comment by JMurph2015** [comment]
Looks good to me, I really like the new autotiling shortcuts, good call not polluting the global hotkey space.

**Comment by JMurph2015** [comment]
@scherepanov I'll let you press the magic merge button this time, feel free whenever you get the chance.

**Comment by scherepanov** [comment]
Merging, and will rollout to EGO
Things that I was not able to easy do:
1) Key binding in preferences. I still cannot find how to remove shortcut. Seems to be code was written for very old version of Gnome, and not working properly now. Need to find sample of working current code for accelerator assignment.
2) Assignable movement keys (left, right, up, down). There is a problem with them, as key chooser (same as on previous issue) do not allow to choose them again.

**Pull request merged**
