### PR TITLE
Add Main window auto tiling presets

### PR DESCRIPTION
**Pull request by danetrata**
Some grid configurations have different sizes when pressed repeatedly like `Super+Alt+KP_5`. Sometimes, I found myself wanting different main window sizes depending on the screen (a 49" ultrawide) and the task at hand.

The change will extend that cyclable presets into the main window auto tiling.

The default configuration is `7/8, 3/4, .625, .5`.

A case could be made to have .5 as the initial size and to remove the change to the `.gitignore`.

### CODE REVIEW

**Comment by scherepanov** [comment]
Interesting... will tr to look over weekend

**Comment by scherepanov** [comment]
Will merge #192 first, then your PR.
#192 has a lot of code changes, makes sense to handle it first.
Most likely, I will ask you to add one more commit, to resolve merge conflicts.

**Comment by scherepanov** [comment]
Works, and look nice.
Can you do two things:
1) reverse order of cyclable presents. First preset should be 0.5. Then, it will be no change for behavior for current users.
2) Add description of feature to README.md, if possible with animated gif (disclaimer - I do not really know how animated pictures are done). This feature is complicated to describe with words, but would be very simple to understand with animated pictures.

**Comment by scherepanov** [comment]
May I suggest one more autotiling feature?
Idea is to pin window, and autotile rest of windows around it.
You are resizing/placing window, and with a shortcut is telling all other windows on monitor to autotile around window you just moved. Window you just moved do not participate in autotiling. With calling repeatedly autotile, you can have various autotile patterns, for example 1, 2, 3,4, 5 vertical or horizontal columns to fit rest of windows in autotiling.
Of course, like any autotiling feature, it would not satisfy vast majority of users, but definitely it will be some that will be using it.
Feature is more flexible that what you just implemented, but do require more keystrokes.
Should not be hard to implement... Let me know if you can do it.
Also, it is interesting, would this feature help you with your workflow, on ultrawide monitor.

**Comment by danetrata** [comment]
> May I suggest one more autotiling feature? ...

That would help with my workflow. With your idea, I would be able to pick out a window in the center then tile the remaining windows around either side

I'll get my PR ready first with the changes from your other comments and then take a crack at this new feature.

**Comment by scherepanov** [comment]
I would say, you will be able to pick up one or more windows in center of monitor, and tile rest of windows around them, either in columns, or in rows.

**Comment by scherepanov** [comment]
After little thinking, may be there are other option that can improve your workflow.
1) Swap windows. gTile will remember previous window that had gTile active on it. By pressing key <swap>, both windows will switch places. 
Use case : you have nicely arranged windows on your monitor, with one window taking a lot of space in center, rest of windows tiled in small sizes around. You want to switch window in center to some other. You set focus on window you want to switch, activate gTile, then switch focus to big window, and press switch. Both windows will swap, and you will get different window taking center stage.
gTile should remember last active window between activations. You can just activate gTile on any window, press <swap> and it will switch places with other window that was activated before.
That should remove need for autotile in your workflow.
2) Move window in previous position. Remember previous window position for last gTile activation. If you activated gTile on any window, press <previous position> will make this window to move to previous position.
That is also related to your workflow. With swap, you will have continuously shuffle smallish window. If you use <previous position>, you will keep your windows layout stable.
I am inclined to thing that gTile should remember window positions and swap windows in tile terms, i.e. grid size and tiles.
Everything should be forced to be along tile grid.

Next:
I do not really like how I implemented autotile in columns. I have 10 keyboard shortcut 1 .. 0, pressing them force windows to arrange in corresponding number 1 - 10 of columns. I have feeling that it is awkward and nobody really using it. AT least on my box, several number keys are not working because they are taken by gnome or something else.
I think right way is to do circular arrangments. It should be one key, and pressing it repeatedly will force to autotile in 1,2,3,4, ... columns. Also, I think it should be 2 keyboard shortcuts - one for arranging in columns, one for arranging in rows.
Next, I think that autotile should be first tried on gTile current grid, and windows should be autotiled on a grid on first invocation. On next invocation, number of columns/rows should be changed, but it should be from number of columns/rows in grid.
Also, due to possible large nubmer of max columns/rows (10), it is not convenient to cycle through them. So, it should be two keyboard shourtcuts - one for increasing, one for decreasing number of columns/rows in autotile.
Please let me know if you are interested in implementing any of this.

**Comment by scherepanov** [comment]
There are conflict with master, can you resolve them?

**Comment by danetrata** [comment]
Yeah I think so. One moment.

**Comment by danetrata** [comment]
The included video doesn't display properly with markdown... Let me make one more change

**Comment by danetrata** [comment]
cUZA5RKK6mEhq

https://user-images.githubusercontent.com/4830810/109256250-4418d580-77bb-11eb-8e50-4764a861cd85.mp4

**Comment by danetrata** [comment]
Didn't realize master started using typescript in more places. I'll need to fix this.

**Comment by scherepanov** [comment]
Code looks good and works.
I found two minor problems:
1) When I am clicking on picture in README.md, it show diagnostics  about corrupted video and not playing it. Hopefully you can fix broken video.
2) You are doing windows size setting without rounding/flooring.
Mar 14 12:27:16 supermedia gnome-shell[1595]: gTile After margins and visible border window is 1280:843**.4285714285714** - 1280:198**.85714285714286**
Mar 14 12:27:16 supermedia gnome-shell[1595]: gTile move_resize_window_with_margins sergey@supermedia:~ 1280:1042.2857142857142 - 1280:198.85714285714286 margin 0 borders invisible 26:23 visible 0:0
For example, you can see it when 6 windows are on terminal, and you are dividing by 5 for caclulating window size.
That is causing subtle rounding errors, and sometimes there is a single pixel gap introduced between windows borders. I had user who rightfully complain about it - he had bright white background and black windows, and when tiling he is seeing bright single pixel line between two windows.
Of course, you just follow code that was there before. I fixed rounding bug for manual move/resize, but never for autotile.
I think right solution is to apply Math.floor to coordinates/size parameters moveResizeWindowsWithMargins. Can you submit PR with it?
For now, I am merging your PR, thanks for contribution!

**Pull request merged**
