### PR TITLE
Feature 54

### PR DESCRIPTION
**Pull request by WBTMagnum**
Here is the promised PR regarding #54. It's probably not the most beautiful implementation, but up until now it does it's job pretty well. If you see room for improvement, just give me a note.

**Some Notes**
1. Regarding the presets: I updated resize presets 1-9. They will start middle-size, grow to the maximum, reduce to the minimum an eventually return to middle-size again (e.g. `4x4 0:2 1:3, 0:1 2:3, 0:0 3:3, 0:3 0:3`). That mimics the behaviour Compiz's tiling application had back in the Gnome2 days.

    Here's a screencast demonstrating the presets
    gtile-demo-resize-cycles

2. Sorry for the excessive white-space changes. I cannot resist such things. If necessary I can dissect them, but I would prefer to leave it that way.

### CODE REVIEW

**Comment by scherepanov** [comment]
Thanks for submitting PR!
Looks like without timeout on cycling through presets, GUI is unpredictable from users standpoint.
If preset is pressed, window can jump to some other position than initial.
Also, this would be very strange for casual users.
Correct approach would be to have timeout (2 seconds). If same preset preset after timeout, it should be forced to first preset in list. That will make more predictability to GUI behavior.
I forgot to mention it at the very beginning, sorry.
That is a simple change - add time of last preset call. If next preset call is after 2 seconds, force it to first preset.
You mention timeout as new feature in your comment - actually it was planned from very beginning.
Let me know if you have bandwidth to implement change.
Otherwise, PR looks good. Over weekend I will be able to do actual testing, but seems to be it will be OK.

**Comment by WBTMagnum** [comment]
Thanks for the feedback. I totally agree. I'll try to squeeze in the timing and window checking in the upcoming days.

**Comment by scherepanov** [comment]
Is it ready for final testing? All implemented?

**Comment by WBTMagnum** [comment]
Almost. Still working on the timeout thingy.

**Comment by scherepanov** [comment]
Thanks, will look today

**Comment by scherepanov** [comment]
Looks good... Sorry took too long... My excuse is similar to "dog eat my homework" (power supply on my home PC burnt, and I cannot commit from office).
Found one thing - schema is not compiled. Attempt to run new version of gTile actually prevented gnome session from start, I cannot login. Apparently, now if some property for extension is missing(in this case it was cycling timeout), it is crashing gnome-shell component "desktop" and whole gnome-session is not starting. Hopefully it will be fixed soon.

You need to compile schema:
cd schemas
glib-compile-schemas .

After compiling schema, gnome session starts properly.

Seems to be I cannot fix this issue by myself in this PR, as it require commit to your branch. Please submit new commit with compiled schema.

And two smaller things.
1) I'd like to have resize preset Super-Alt-5 to grow from center outwards. It will be in line with behaviour of other Super-Alt-X presets - they start from position and growing outwards.
Please change in XML definition of preset to 
                <key type = "s" name="resize5">
                        <default>'8x8 2:2 5:5, 1:1 6:6,0:0 7:7,16x16 5:5 9:9'</default>
                        <summary>Preset resize5 settings.</summary>
                </key>

2) Can you add one more line of docs to README.md.
Say that presets can be configured cyclable, if you will specify more than one settings. Or something like this. Right now it is not clear that cyclable presets do exist.

**Comment by scherepanov** [comment]
How does it look for you
Let me know if you can do above fixes.
If you do not have time, I can merge as-is and submit fix by myself.

**Comment by WBTMagnum** [comment]
Sorry for the compiled schema mess up. I compiled it in my local installation only, but not in the repository. Therefore I didn't see any changes in the diff and assumed the compiled schema is not part of the repository and compiled automatically on installation. Anyhow, that's fixed now.

I also updated `resize5` preset according to your proposal.

Additionally I prepared an update to README.md, but did not include it into the PR. I would prefer to add this separately with a bunch of other changes I prepared for the readme.

**Pull request merged**
