### PR TITLE
Keyboard presets should be on by default. Bottom panel should be off …

### PR DESCRIPTION
**Pull request by scherepanov**
…by default, to match vanilla Gnome install

### CODE REVIEW

**Comment by scherepanov** [comment]
@StuntsPT If you have time, can you look and review/approve this?
It is last thing before I can put it on e.g.o.

**Comment by JMurph2015** [comment]
So, I'm a little hesitant to pollute the global accelerators with so many more keybindings by default?  Am I missing something about that presets change?

**Comment by scherepanov** [comment]
Global keyboard presets are prime feature of gTile. They were always intended to be enabled by default, I am not sure why it is disabled in code, probably slip in from debug time.
I spend time to make sure defined global presets so they are not interfere with Gnome built-ins. All presets are localized on keypad, with Super+(Alt,Shift,Ctrl) modifiers.
For rest of key bindings, only Super-KP_Enter is active all the time. Other keys are activated when interactive window is open, and deactivated when closed. Very non-intrusive.
BTW I did same way with catching global events, for title change. It is active only interactive window is activated.
Personally, I consider mouse control as obsolete and never use it. But it is a good marketing thing and looks pretty good. I had thoughts to issue separate extension without mouse control, only keyboard presets/control, but decided to leave it in place as it cost not a lot to keep them in code.
And leaving keyboard presets disabled by default will confuse users.
Please review/approve last PR. It will be ready for prime time. I got access to e.g.o. gTile, will put new version out tonight.

**Comment by JMurph2015** [comment]
If all of the presets are on the keypad, then I can get behind that one, I just don't wan't to conflict with other popular accelerators by spamming the global accelerators with a bunch of ours.

**Comment by scherepanov** [comment]
Thanks! Will roll out to e.g.o. late tonight.

**Comment by StuntsPT** [comment]
Sorry! I guess I was late to the party today. =-)

**Pull request merged**
