### PR TITLE
Remove depr lang

### LINKED ISSUE #233: Remove deprecated Lang
From EGO gTile review:

3. Lang is a deprecated module. Please remove it for the next version:
https://wiki.gnome.org/Projects/GnomeShell/Extensions/Review#General_Advice
Learn how to remove Lang from your code:
https://gjs.guide/guides/gjs/legacy-class-syntax.html

### PR DESCRIPTION
**Pull request by extremegf**
Fixes #233

### CODE REVIEW

**Comment by scherepanov** [comment]
Great!!!!
Merging...

**Comment by scherepanov** [comment]
Do you have any time to do some work on gTile?
There are a bunch of improvements can be done.
My guess, exporting/importing settings to/from a file would be very used feature.
Ideally, gTile should come with bunch of canned settings, each designed with different style. I just heard about very interesting style of settings from @mchristiansen, we just merged his PR to make it work better. gTile does have a lot of users, and it is not possible to satisfy all of them with single settings.
Users should be able to save his own settings into file, with description inside file. Then, send to github by submitting PR, adding new file with settings.
Then, browse available settings. Each settings should have some description, and description should be shown to user.
User should be able to pick whatever settings he would like.
I designed current set of default shortcuts by myself, and they are not ideal, serving more like a demo. It is interesting that vast majority of users are actually using them. That is not good, users should have more choice. Like for wide horizontal screen, vertical screen etc.
Are you interesting in implementing that?
If you have any feature that you would be interested to add to gTile, let me know. I can see mild demand for various autotiling features, though they will mostly have limited users audience.

**Comment by extremegf** [comment]
Hmm, the settings import export is a nice first step for this Configuration Profiles feature you mention. 

I don't have all that much free time, but I can look into it to see how hard might this export be. Gnome already stores these settings anyway...

**Comment by scherepanov** [comment]
Great!
Your contribution is really appreciated!

**Comment by extremegf** [comment]
Thanks :)

**Pull request merged**
