### PR TITLE
use full screen for single window in AutoTileMain + fix duplicated var initialization

### PR DESCRIPTION
**Pull request by iskrid**
The PR:
- removes a duplicated var initialization which avoid the plugin's pref pane to open
- introduce a small behavior change of the AutoTileMain -> the Main window uses the full screen width if it's the only window on the monitor

### CODE REVIEW

**Comment by scherepanov** [comment]
Thanks for submitting PR. I will check on it shortly.

**Comment by scherepanov** [comment]
Thanks for submitting this PR.
1) duplicated "let text" fixed in another PR that is about to be merged
2) "use full screen if only window for autotile" is actually a good idea, and will be merged into master
3) Autotile shortcuts were specifically excluded from global keys. gTile is polluting global keys space and interfere with a lot of other program / extensions etc. As you noticed, autotile shortcuts are activated only when gTile window is visible.
I do agree that some users will benefit from having global keys for autotile.
I suggest that you will add settings in preferences - global autotile shortcuts. It is off by default, and autotile shortcuts is same as now. If setting is on, autotile shortcuts will became global.
That will satisfy needs for wider user population.
Let me know how it sounds for you.

**Comment by iskrid** [comment]
Hi,
1. and 2. great thx

3. I'll revert the current changes, create a new branch, change it as you propose it and create a new PR, I think/hope it's ok for you :)

**Comment by iskrid** [comment]
Hi @scherepanov ,
the MR contains now only 1. and 2.

**Comment by scherepanov** [comment]
Thanks!
PR looks good, but 1) will create a conflict with large pending PR (#54) that is about to be pushed into master.
I will merge into master as soon as this PR will make into it.
Will wait for new PR for 3), definitely it will be a good improvement.

**Pull request merged**
