### PR TITLE
Support Gnome 40

### PR DESCRIPTION
**Pull request by StephanDollberg**
Requires a few changes to pref.js for gtk3 to gtk4 migration.

For backwards incompatible changes we guard the new code with a version
check to still support gtk3.

### CODE REVIEW

**Comment by oturpe** [comment]
I am not involved with this project in any way apart from being a user on Gnome 40, but I might as well comment:

Use `let` here, `var` is discouraged nowadays:
```
var _ok, key, mods;
```

**Comment by scherepanov** [comment]
Thanks for comments.
@StephanDollberg can you commit with change?

**Comment by scherepanov** [comment]
Checked/tested on gnome-shell 3.38.4. Works properly.
Now will upgrade to gnome-shell v 40 (Fedora 34), will test there.

**Comment by StephanDollberg** [comment]
@oturpe thanks fixed, didn't know let worked with no direct assignment.

**Comment by scherepanov** [comment]
Tested - works fine on gnome-shell v 40.0
Will add one more commit - modify metadata.json to allow v 40, and do release on EGO
Thanks for help!
It you have some spare time on your hands, may be you can look on re-writing preferences dialog as GTK application?
That is merely writing XML to describe all tables/fields/radio buttons etc.

**Review by scherepanov — APPROVED** [review]

**Pull request merged**
