### PR TITLE
Fix gTile for GNOME >= 3.30

### PR DESCRIPTION
**Pull request by luisbc92**
As described at https://github.com/micheleg/dash-to-dock/pull/770, all workspace related features that used to be on **global.screen** have moved to **global.workspace_manager**.

The fix enables gTile to work on all GNOME <= 3.30.

NOTE: That the diff shows a bunch of changes but most of it was white-space removed by my linter.

### CODE REVIEW

**Comment by StuntsPT** [comment]
Can you please, please turn this into 2 separate commits? One for fixing the issue, and one for code linting (which I also find important).
The linter part make reviewing the commit a lot harder than it should have to be.
Thank you!

**Comment by luisbc92** [comment]
No problem, should have done that in the first place.

It should now be two separate commits.

**Comment by scherepanov** [comment]
Can you verify that your changes working on gnome-shell < 3.30, for example on gnome-shell 3.28.

**Comment by luisbc92** [comment]
Yes, the WorkspaceManager object is declared as:

var WorkspaceManager = global.screen || global.workspace_manager;

Since global.workspace_manager does not exist on GNOME <= 3.28, it gets set to global.screen instead. The opposite is true for >= 3.30.

**Comment by luisbc92** [comment]
This is a tested approach as implemented here:

https://github.com/micheleg/dash-to-dock/pull/770

**Comment by StuntsPT** [comment]
I can confirm that with this patch gTile is still working with gnome-shell 3.28.x.
I also like what you did with the removal of all that unnecessary whitespace!
I just have one question - why change `hotkeys` to `Hotkeys`? I have nothing against that, it's just pure curiosity from someone who know very little about JS specifics.

**Comment by luisbc92** [comment]
It was not a required change, but I felt that uppercase Hotkeys was more consistent with how all other imports were named (Settings for example).

But more than anything, that was me being OCD.

**Comment by scherepanov** [comment]
PR looks good
I will put new version on EGO
Please note that EGO does not allow to list future versions of gnome-shell. New version of gTile will be there listed as supporting maximum gnome-shell v3.28.

**Pull request merged**
