### PR TITLE
Position gTile overlay in the center of the focused window

### PR DESCRIPTION
**Pull request by schnz**
Addresses #352 and #353.

### CODE REVIEW

**Comment by scherepanov** [comment]
Works great, thanks!
Now it looks much better for keyboard guys!

Though, behavior a little bit weird when mouse pointer will be in the middle of gTile window. It will show one active cell.  As soon as you will move with keyboard shortcuts, it will became normal.

Still, it is soo much better than before for keyboard-only use!

Please merge!

This change deserve separate release.

I think, we need to set default "Close gTile after confirming operation", but it is minor thing.

---------------------

I noticed that windows resizing with keyboard shortcuts is not 'bouncy'. (I am on older Gnome desktop and still using previous version of gTile, and had not a lot of chances to test new interface).

We are shrinking window when you are moving into border. When you are moving away from border, window will expand to original size and then continue to move away from border. Now, when you move away from border, it stays same shrinked size. Bouncy behavior looked very cool and was very intuitive.

**Comment by scherepanov** [comment]
Hi @schnz 
I read docs - question:
We used to support negative values in resize preset coordinates, meaning "counting from opposite side of grid".
is new code support it as well, or it was removed?
I think we should mention in docs about syntax that tile grid coordinates are starting with 0.

**Comment by schnz** [comment]
I've updated the PR once again to allow toggling between the overlay placement modes.

---

> Though, behavior a little bit weird when mouse pointer will be in the middle of gTile window. It will show one active cell. As soon as you will move with keyboard shortcuts, it will became normal.

To me it feels less wired than moving the overlay to an unexpected (alternative) position. Like [I mentioned](https://github.com/gTile/gTile/issues/352#issuecomment-1946093683), I would really love a suggestion for a solution that pleases everyone.

---

> I think, we need to set default "Close gTile after confirming operation", but it is minor thing.

It is already set as default. Please elaborate.

---

> I noticed that windows resizing with keyboard shortcuts is not 'bouncy'. (I am on older Gnome desktop and still using previous version of gTile, and had not a lot of chances to test new interface).

The memorization of the grid selection size while panning is a different topic. Best document it in a different issue if you don't want it to be forgotten. I most likely will not implement it - but of course it's possible to create a PR for this.

---

>  We used to support negative values in resize preset coordinates, meaning "counting from opposite side of grid".
is new code support it as well, or it was removed?

It was removed as part of the rewrite:

> Only static grid sizes are supported for presets, e.g. 3x3 1:1 1:1, 2:2 2:2. The more sophisticated syntax with negative offsets and window placement by percentages is not supported and probably won't be supported unless there is demand for it.
-- **Source**: https://github.com/gTile/gTile/pull/341#issue-1974759748

---

> I think we should mention in docs about syntax that tile grid coordinates are starting with 1.

Of course - please feel free to add it to the README. As far as I remember, I haven't touched that section in the README file - other than  removing the parts with the negative and relative offsets.

**Comment by scherepanov** [comment]
@schnz thanks for explanations! 
Yes, "autoclose gTile" is set by default. 
Will merge this PR.

For overlay placement conflict with cursor position. 

First, this is not that of a big deal, though slightly annoying. Nothing breaks.

On my 43'' monitor shift of overlay position is not noticeable (I am using old gTile). Conflict with mouse position does not happens often.

When you have a small monitor, yes, shift is more pronounced. Still it is manageable and not breaking workflow.

We can actually make overlay shift smaller. We need to avoid only area in overlay window with tiles, and this is half of overlay size. That will make it even less noticeable.

FYI I found a very nice video on youtube https://www.youtube.com/watch?v=R2k9PG-TXFE
It has 3.5 minutes about gTile, and very nicely explain what it is and how it works. Video points that prime advantage of gTile is a keyboard interface. I kinda agree with this statement, other two extensions reviewed in video - Forge and Tiling Assistant - are extremely impressive and using mouse interface. I am very happy that gTile is considered good enough to be compared to those very impressive extensions.

I want to ask help from gTile user community to create 4 min video about gTile, with plans to put it very first in docs, after short message what is gTile. Let me know what you think.

**Comment by schnz** [comment]
> I want to ask help from gTile user community to create 4 min video about gTile, with plans to put it very first in docs, after short message what is gTile. Let me know what you think.

I believe gTile could also massively benefit from a renewed EGO preview gif graphic, similar to how other extensions present themselves:

- https://extensions.gnome.org/extension/4702/awesome-tiles/
- https://extensions.gnome.org/extension/4548/tactile/
- https://extensions.gnome.org/extension/1604/arrange-windows/

**Pull request merged**
