### PR TITLE
Add keyboard shortcut for moving window to next monitor.

### PR DESCRIPTION
**Pull request by gonzojive**
Gnome offers a shortcut for moving a monitor to the monitor to the left, right,
up, or down. This requires 4 keybindings. The approach implemented in this PR requires only one
keybinding. Also, in my experience, it is less mental effort and quicker to repeatedly hit
the "move-to-next-monitor" shortcut compared to hitting multiple keys depending on where the window is.

The change adds a new tilespec.ts file for parsing gTile-formatted rectangle
specifications. This was copied from the "bazelify" branch of
github.com/gonzojive/gTile. Future refactoring should use this for parsing and
printing tile specification strings instead of the current code in app.ts.

### CODE REVIEW

**Comment by scherepanov** [comment]
Hi, yes, this is a good ideas - shortcut to circle windows, and new syntax for rectangle.
Will check and test this weekend.
Meantime, can you look on big problem - mouse interface is broken?
When we switched to typescript, rewrite introduced strange bug, and mouse interface is extremely misbehaving. For example, you cannot select most right-lower tile, move mouse over last row is not working. If you are using mouse interface, then gTile window popup when I am going to menu etc.
I missed it because I am 100% using keyboard interface only.
I found couple things - syntax that you did, something like "v from collection" not working, you have get keys and take index by key.
I tried to dig more, but so far no luck.
I will really appreciate if you will look on mouse interface bug.
You can refer to v35, it has properly working mouse interface, as baseline. Next we did a switch to bazelified build, and it is where it gets broken.

**Comment by gonzojive** [comment]
Unfortunately, I don't have bandwidth to look into the mouse issues. I don't even know what the mouse interface looks like. I suspect it's a pretty simple bug.

**Comment by scherepanov** [comment]
Finally got some time to look on your code, sorry took longer than expected.
I can see you add new global shortcut for moving windows to next workplace. 
Also, you added file tilespec.ts, for new format of specifying window sizes. But you actually never using it in app.ts, it is still using current format.
What are you plans - are you going to submit PR to start using new tilespecs?

**Comment by gonzojive** [comment]
Eventually, yes, tilespec can be used for all the parsing.

**Comment by scherepanov** [comment]
Sorry did not answer for long time, my domain expired and I did not notice.
Would you mind if I will delete tilespec file?
I do not see any plans from anybody (except you) in future to use this new spec.
I will gladly commit this file, if you will submit any code that will actually use it.
I have not problems committing your new keyboard shortcut for cycling window through workspaces.

**Comment by gonzojive** [comment]
The tilespec code is a refactor of the existing parsing. It is used in one
location in app.ts and can easily be used by others after some needed
refactoring.

**Comment by gonzojive** [comment]
It can be deleted, but the new functionality will break unless code changes
are made.

**Comment by scherepanov** [comment]
Attempt to run code from your PR produces error, see below error text and trace. It is immediately followed by coredump and gnome-shell restart.
Attempt to compile settings xml does not help.
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: gTile showTiling
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: gTile Mouse x 717 y 393 is inside grid actor rectangle, changing actor X from 609 to 877, Y from 349.5 to 546.5
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: gTile _onFocus 
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: gTile resetFocusMetaWindow
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: gTile _onFocus scherepanov@chi-fed26-scherepanov:~
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: gTile title: Terminal - scherepanov@chi-fed26-scherepanov:~
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: gTile moveGrids
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: gTile Mouse x 717 y 393 is inside grid actor rectangle, changing actor X from 609 to 877, Y from 349.5 to 546.5
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: gTile Binding keys
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: Settings schema 'org.gnome.shell.extensions.gtile' does not contain a key named 'resize-right'
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: == Stack trace for context 0x558bc145e2a0 ==
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: #0   7ffe09324b30 b   resource:///org/gnome/shell/ui/windowManager.js:1127 (11953a9cd2e0 @ 41)
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: #1   7ffe09324c40 b   /home/scherepanov/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:195 (1c770cd8db50 @ 161)
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: #2   558bc1a49f38 i   /home/scherepanov/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1323 (1c770cd8a2e0 @ 31)
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: #3   558bc1a49e08 i   /home/scherepanov/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1210 (1c770cd8a740 @ 1455)
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: #4   558bc1a49d80 i   /home/scherepanov/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1232 (1c770cd8a6a0 @ 49)
Dec 05 16:26:10 chi-fed26-scherepanov gnome-shell[287294]: #5   558bc1a49cf8 i   /home/scherepanov/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:676 (1c770cd8c920 @ 10)

**Comment by scherepanov** [comment]
Can you submit one more PR, with your refactoring for mouse interface?
Even if it is not fixing problem, refactoring would be a big welcome.

**Comment by scherepanov** [comment]
Merged as #192

**Pull request closed without merging**
