### PR TITLE
Allow shrinking selection on move right or down

### PR DESCRIPTION
**Pull request by extremegf**
Hello, I use and absolutely love gTile!

This PR allows for the move shortcuts to shrink selection if it hits right or bottom edge of the grid. This enables the following workflow:

1. Activate Meta+Enter
2. Position top left corner with HJKL
3. Position bottom right corner with Shift+HJKL

Without this shrinking behaviour, I often end up moving, then shrinking to size, then moving again. 

I imagine that the biggest problem with this change is that it modifies the default behaviour and not everybody might like it.
If thats a problem, I can add a config checkbox to enable this.

Thanks!

### CODE REVIEW

**Comment by scherepanov** [comment]
Cool!
I though about it, but decided on current behavior.
It is correct, a lot of people would not like change.
Please add settings to enable new behavior, default should be old.
Of course, docs should be updated to describe it, preferably with some cool demo video running in a loop.
I have not look at code yet, but I assume, that new behavior apply not only to HJKL, but to move/resize with arrows as well?
Will test as soon as you will submit PR with settings that will enable this behavior.

**Comment by extremegf** [comment]
Let me track this here:

- [ ] Add setting, disabled default
- [ ] Document, preferably anim
- [x] Works with arrows and HJKL
- [ ] Fix "3x2 bug"

I've noticed that the grid does not refresh correclty on 3x2 moving down. Works fine on 6x6 and 2x2. I'll investigate and add a fix.

**Comment by scherepanov** [comment]
You got it, that is exactly what is needed to merge your PR into master.
If you suspect problems with 3 x 2, I would strongly suggest to test all edge cases, like 1 x 1, 1 x 2, 2 x 1, 1 x N, N x 1, 2 x N, N x 2.
As you are modifying basic behavior of keyboard move/resize, would be nice if you will do anim for docs explaining both - how it is working by default, how it works with your option enabled. That would be much easier for users to understand what your option is doing.

**Comment by extremegf** [comment]
The implementation is ready. Now I just need to record the doc videos.

**Comment by scherepanov** [comment]
Great!

**Comment by scherepanov** [comment]
Are you done with this PR?

**Comment by scherepanov** [comment]
Yes, window now shrinks when you hit a border on move.
If you will move window back to center of screen, window stays shrunk.
That makes for undesired behavior - if you will accidentally hit border, you shrink window, and it stays shrunk even if you did it on accident. Most likely user want to keep window size same, only move window.
I think good behavior would be to restore original window size if user move window back to center of screen.
That would do more natural behavior: user will move window around screen, if it hits border it shrinks, if it move back from border it restore size up to original. Should work if you will contact any edge, up/down/left/right. 

What do you think about this behavior? I am looking for more natural and predictable way of border resize behavior.

Of course, what you implemented is working just fine.

**Comment by extremegf** [comment]
I gave it some thought and I like it. This behaviour would allow me to position windows in the corners without using Shift key most of the time. If I go to far I can just go back without losing the initial size. 

I'll see if I can find a way to implemnt this. It's harder as currently we only store the start point and end point of selection, and these have to be valid grid cells. I'll try to make a prototype and we'll see.

**Comment by scherepanov** [comment]
Great!
I actually like how it will work. Behavior would be completely natural and very intuitive.
I think it will be safe to remove option from preferences, and make it the only way how gTile works.

**Comment by extremegf** [comment]
I'll post the new implementation as a separate PR, as I started over from master.

**Comment by scherepanov** [comment]
That would be great!

**Comment by scherepanov** [comment]
Superseded by #249

**Pull request closed without merging**
