### PR TITLE
Honor window-margin when laying out windows

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Comment by luksa** [comment]
Latest commit fixes how the margin is applied and makes the changes in this PR much more trivial.

**Comment by schnz** [comment]
Thanks @luksa. The first contribution to an not even merged rewrite, hehe.

To be honest, I had totally overlooked that window margins was a thing in gTile. Although I would probably have realized it by the time I completed the preferences dialog.

I am not yet entirely sure were to best place the margin logic. As in: Is the margin a property of the window and thus applied as an afterthought after moving/resizing a window? Or is it a property of the grid and thus each tile is considered to have an explicit margin.  This would effect how other features are working (such as the window-placement preview or the autogrow feature).

Appreciate your effort but I will have to give this some thought.

**Comment by schnz** [comment]
I gave this a long thought now and I come to the conclusion that the original design is flawed in the first place. I won't implement it in the same way that it was beforehand.

The original extension has both insets (a margin applied to the monitor's work area) _and_ window margins which are applied in addition to the inset if a window is positioned on either of the screen edges. And to top it all of, there is an option to disable margins if you resize a window full-screen (i.e., to the size of the whole grid). 

So I asked myself if this would satisfy any real use case scenario and I cannot come up with a single case where this makes sense. Why would I want to have margins and insets "stack" on top of each other? Either I want to have insets to avoid windows to occupy certain edges on my screen _or_ I want to have window margins to make it look better (I suppose). Maybe I event want both of it, but then again, I wouldn't want that inset and window margins add to each other because then I would have to manually reduce my inset by my margin so that it behave like I want it to behave.

In my mind, if both options (inset & window margins) are kept, then the only option that makes sense, would be to have insets _only_ apply to the screen edges and margins _only_ to apply towards the "inner" screen, effectively allowing windows with margins to snap with the screen edges. This would automatically render the option to remove the margin for full-screen sized windows unnecessary because there won't be any margins to windows positioned at the screen edges. And if I want there to be a margin, I can setup the inset. And if I want full screen windows to occupy my whole screen I use the <kbd>Alt+Enter</kbd> shortcut of Gnome. And if I am unhappy then that the window is hiding my Gnome task bar then so be it - I don't consider this a usecase I am willing to support because it makes the codebase _that_ much more complicated.

I'll leave this PR open for a few more days in case there is some feedback to that decision that would make me reconsider this (most likely from you @luksa  or from @scherepanov).  Otherwise I am going to implement it the way I described.

**Comment by luksa** [comment]
> In my mind, if both options (inset & window margins) are kept, then the only option that makes sense, would be to have insets only apply to the screen edges and margins only to apply towards the "inner" screen, effectively allowing windows with margins to snap with the screen edges. 

This is exactly what I implemented in the 1st commit of this PR. Here's a visual representation of the behavior:

gtile

Then I realized that this doesn't match the previous behavior. Also, it isn't correct to call this spacing between windows `window-margin`. It should be called `window-spacing`.

So, we both agree that stacking insets and window margin doesn't make sense. As a user, I just want the ability to add some type of padding around my windows to make things look nice. 

Note: I did see some old comment from @scherepanov I believe, where he said that `window-margin` could replace `insets`, but that would result in the inability to make the inner spacing match the insets, as it would always be twice as large, which wouldn't look as nice.

> I could also use Super+Up to have my window take the full-screen without insets/margins being applied. This should really fit everybody's need.

This is the approach I've always used.

**Comment by schnz** [comment]
100% agree. Nice graphic btw. Do you mind if I incorporate that in the README?

I also agree that it shouldn't be called "margin". "spacing" would be a better wording. The only reason to keep the old wording would be backward compatibility for the settings. But since the behavior changed it would break the experience anyway. I will rename the setting accordingly in the next commit.

> window-margin could replace insets, but that would result in the inability to make the inner spacing match the insets, as it would always be twice as large, which wouldn't look as nice.

I thought about this as well. I thought about having margins behave similar to CSS margins in that they collapse to one another and do not stack. But since "insets" were implemented as 4 different configurable values (top/bottom/left/right) I thought that they serve a different purpose, e.g., when I want keep a part of my screen free from windows (maybe because I have some sort of [OSD](https://github.com/brndnmtthws/conky)).

**Comment by luksa** [comment]
@schnz sure, you can use the graphic. Here's the source in case you'll want to copy it and make any changes (note: I've already changed `window-margin` to `window-spacing`): https://docs.google.com/presentation/d/1FXDBWGEEYwmGlts-uEEplPVDpuYhqruSRLM9EIdACUo/edit?usp=sharing

**Comment by schnz** [comment]
I've put the image to the README. This should clarify the concept to everyone pretty good. Thank you!

I am going to close this PR. The feature is implemented in the latest version as discussed.

**Pull request closed without merging**
