### PR TITLE
changing the icon to work for dark or light themes

### PR DESCRIPTION
**Pull request by jvonhoff**
For #203 
My inkscape skills are terrible, but I gave it a shot.  Also, I didn't figure out how bazel works, but these changes work fine when I apply them to my local install.
New light mode:
image
New dark mode:
image

### CODE REVIEW

**Comment by scherepanov** [comment]
Thanks for PR.
I need to do some reading and more testing how it works.

**Comment by jvonhoff** [comment]
Any additional conversation on this PR?

**Comment by scherepanov** [comment]
I do appreciate your efforts that went into looking at problem and issuing PR.
I cannot merge it right away, I need to understand what is going on.
Unfortunately, recently I am extremely busy on my day job.
May be, someone else from gTile team can look on it.
Otherwise, it has to wait. Sorry.

**Comment by jvonhoff** [comment]
No worries, just wanted to help if there's an issue.

**Comment by scherepanov** [comment]
Merged with #227, as part of bigger efforts for adding styles to gTile.
Thanks for contribution!

**Pull request closed without merging**
