### PR TITLE
GNOME 40 like styling

### PR DESCRIPTION
**Pull request by canerakdas**
I've been using this great extension for a while, I tried to edit it to match the current shell design on GNOME 40.

This is my first time styling a GNOME extension, I welcome your reviews and comments.

Preview
gTile

### CODE REVIEW

**Comment by scherepanov** [comment]
Great!
It would be very natural if you will incorporate light/dark icon style from #204
Can you review it and add to your PR?

**Comment by canerakdas** [comment]
@scherepanov Sure, I'm starting to working on it :+1: 

Thank you

**Comment by scherepanov** [comment]
Great!
I do not have much time during weekdays. Usually will be able to review over weekend

**Comment by ashrude** [comment]
hi, I probably should have checked the pull requests before I started doing the same thing 😅 anyway, here's my go at it

gTile_dark

gtile_light

I don't have the javascript skills to put light/dark mode in the settings, so there are two css files. (one named stylesheet.css, and one named stylesheet_light.css)

I also redrew all the icons as SVGs so I could change the colours

[heres my fork](https://github.com/ashrude/gTile)

**Comment by scherepanov** [comment]
Great!

We have at least 4 styles:
1) current
2) matching Gnome styling from @canerakdas 
3) Light and dark modes from @ashrude 
We also have light and dark icons from @jvonhoff in #204 

Definitely it is time to add more styling to gTile.

I think good idea would be to incorporate all above styling into gTile distribution, and allow to choose style in settings.
Limiting styling to one choice is not going to do well in open source project. It will be always some users who will be unhappy. We need to allow users to select any styling they want. 
Matching Gnome styling would be a good default option. Though I do agree that less dead space would be better (disclaimer - I am not a GUI designer and I tend to see things more from functionality side than from nice look side).
I think it is possible to have several styling inside single css file, and have single switch that selects different style.

@canerakdas can you look into it?

**Comment by canerakdas** [comment]
Sounds great! @scherepanov 

Also, I'm thinking to add a naming convention to classes.
With the documentation, open-source devs easily can edit/implement their styles.

If I have any questions, I'll be asking here, thanks all

**Comment by scherepanov** [comment]
Great! Will review/test over weekend.

**Comment by canerakdas** [comment]
Hey @scherepanov . I'm working on the documentation. I will try to document how people can implement their styles.

@ashrude  I implemented your themes, as named "Minimal Light" and "Minimal Dark". If you want a specific name I can change it for you.

Also, I'm not sure about the  @jvonhoff's pr, also we need to implement the hover and active states. IMHO If we accept this, panel icons will be managed as hard-coded, a choice must be made here.

Should these icons be managed on a theme-based basis via CSS or should all themes have these icons?

**Comment by scherepanov** [comment]
I think we will abandon #204, everything is inside your PR.
I will leave up to you how implement icon management, you absolutely have more expertise in this area than I do.

**Comment by canerakdas** [comment]
PR ready for your review :tada: @scherepanov

**Comment by scherepanov** [comment]
Geeat!
Will do over weekend.

**Comment by scherepanov** [comment]
Did some checks on new code.
It is very impressive, we now have 4 themes, and can chose theme in preferences.
There are glitches. If I am enabling gTile window by clicking on icon, or using keyboard shortcut Super-Enter, mouse interface now working - click is being propagated to underlying window and not caught by gTile window itself. I cannot resize window with mouse. If I move underlying window away, mouse interface start working.
Keyboard interface works properly.
That may be a bug in gnome-shell. I am on gnome-shell v 40. Will try to upgrade to most recent Fedora code. Will keep you posted.

**Comment by scherepanov** [comment]
Yes, software upgrade fixed problems, gTile now function properly.
I found two problems:
1) I am using Dash To Panel extension. It is very popular, number two for downloads for current version of gnome-shell.
gTile icon is not visible on Dash To Panel. It used to be visible just fine.
If I am disabling Dash To Panel extension, gTile icon became visible and works properly.
Can you install Dash To Panel, enable it, and see what happens. Something like system background etc????
2) For Classic theme, background tiling preview (semi-transparent preview of window placement) does nto work when changing theme.
I was changing theme from Default->Classic->Lightweight->Minimal Dark ->Minimal light and back to Default. Each time I am coming to Classic theme, background tiling preview does not work.
This issue is reproducable each time.
Can you look on both issues.
Let me know if you have any quesitons.

**Comment by canerakdas** [comment]
@scherepanov thank you for the review, I plan to solve it this week. :+1:

**Comment by canerakdas** [comment]
Hey @scherepanov,

1. I tried this problem but could not reproduce it. Can you share more information about this problem?

My configuration is:
  - GNOME Shell 40.4
  - Dash-to-Panel 43
  - gTile with the default theme
 
 Panel preview:
Untitled

2. This problem was caused by misspelling the pseudo-class name in CSS, fixed it.

**Comment by scherepanov** [comment]
Checking now.
Current master have exactly same problem as 2). At least, you are not introducing any new bug or strange behavior.
This is little bit funky bug, as it can appear, or it can work properly. Most likely it is gnome-shell problem, hopefully will be resolved after some gnome-shell upgrade.
My conclusion that it is good enough.
For problem 1), it is fixed, works properly.
I am merging into master. Thanks for contribution?
If you have more energy, would you mind to look on preferences dialog?
Would be very nice If you convert preferences dialog to default Gnome style.
Would be perfect if you can convert preferences dialog to GTK+, with styling.

**Comment by canerakdas** [comment]
Thanks for your feedback @dverbru ,

For the default theme, I think we can apply a different solution instead of removing these margins completely here.

When the number of columns in the grid is below a certain number, these margins stop, but when the number of columns/rows exceeds the limit we will set, they switch to the non-margin version.

Since the margins given in the grid are not proportional to the size of the grid, these margins are meaningless if there are too many columns/rows as you specify.

@scherepanov If you have different feedback here we can also apply different solutions

**Pull request merged**
