### PR TITLE
docs: mention that the schema needs to be recompiled

### PR DESCRIPTION
**Pull request by sorin-davidoi**

### CODE REVIEW

**Comment by scherepanov** [comment]
That is a good point. I am doing it manually each time I am modifying schema xml.
In my opinion, correct approach is to include schema recompile in Basel build.
That would be completely transparent and will do a job.
I am not a big fan of putting additional info in README - it serves as prime docs reference for users, trying to keep it small.
Please submit PR with Basel schema recompilation, I will merge it.
For now, I will reject this PR.

**Comment by sorin-davidoi** [comment]
I wasted 15 minutes in https://github.com/gTile/gTile/pull/170 trying to figure out why the extension didn't load. What is the harm of mentioning this until the Bazel build is adjusted? If not as a step that at least a note under the steps.

**Comment by sorin-davidoi** [comment]
> I am not a big fan of putting additional info in README

This is a change to `DEVELOPING.md` though.

**Comment by scherepanov** [comment]
You will be surprised. With large user base, there are users who a pushing for smallest possible README.
DEVELOPING.md would do.
Please go wild, put there as much info about development as you can. Will merge.

**Comment by sorin-davidoi** [comment]
I can't reopen the PR but I think you can. Please reopen and merge if that is the case.

**Comment by scherepanov** [comment]
Yes, I should be reading better. I had an impression this is for README. Merging.

**Pull request merged**
