### PR TITLE
Expand documentation of resize presets

### PR DESCRIPTION
**Pull request by con-f-use**
See offtopic discussion on issue https://github.com/gTile/gTile/issues/79 for more details.

### CODE REVIEW

**Comment by scherepanov** [comment]
Looks perfect, big thanks!
2 typos:
prefs.js - line 257 - cloumns 
gschema.xml - line 410 movea

Please submit fix, and PR will be merged.

BTW any way I can edit someone else PR? From what I know only PR author can make any change. Is it correct?
I would like to do changes like above by myself, just to save time.

**Comment by con-f-use** [comment]
Only if the PR-author adds you as contributor to his private fork, which I normally do but forgot this time.

**Comment by scherepanov** [comment]
:-)
Now instead of cloums we have cloumns
Definitely new spelling is better than original!

**Comment by con-f-use** [comment]
I don't follow. What's wrong with [columns](https://en.wiktionary.org/wiki/column#Noun)?
At any rate, you can use your new edit privileges to correct ;-)

**Pull request merged**
