### PR TITLE
Add keyboard shortcut for moving window to next monitor.

### PR DESCRIPTION
**Pull request by gonzojive**
Gnome offers a shortcut for moving a monitor to the monitor to the left, right,
up, or down. This requires 4 keybindings. This approach requires only one
keybinding. Also, in my experience, it is less mental effort to repeatedly hit
the "move-to-next-monitor" shortcut repeatedly.

The change adds a new tilespec.ts file for parsing gTile-formatted rectangle
specifications. This was copied from the "bazelify" branch of
github.com/gonzojive/gTile. Future refactoring should use this for parsing and
printing tile specification strings instead of the current code in app.ts.Gnome offers a shortcut for moving a monitor to the monitor to the left, right,
up, or down. This requires 4 keybindings. This approach requires only one
keybinding. Also, in my experience, it is less mental effort to repeatedly hit
the "move-to-next-monitor" shortcut repeatedly.

There are also numerous new type definitions, including the generated "settings_data.ts" file based on the contents of the gnome schema xml file. Overall these changes increase the type safety of the plugin and are no-ops from a user experience perspective.

### CODE REVIEW

**Comment by scherepanov** [comment]
Have you resolved issue with missing key from conf?

**Comment by gonzojive** [comment]
I'm not aware of the 'missing key from conf' issue. May you please explain?

I think this change is probably safe to merge. It is almost all refactoring aside from the "move to next window" change, which we can disable if you'd like. As far as I can tell, the GUI still works.

**Comment by scherepanov** [comment]
Let me know when you are done (in not way it means I want you to stop making changes, please continue to do so!)

**Comment by scherepanov** [comment]
Found bug with mouse interface.
1) Move window with mouse - <Super>Enter, click on one cell, click on other cell.
2) Try to move window with mouse again. <Super>Enter, move mouse to gTile window. You do not see orange rectangle and grid element selection. It require clicking once on gTile window, for selection to appear. Also, you can move mouse out of gTile window and back, then selection will appear.

**Comment by gonzojive** [comment]
I'd be happy to get everything merged into master once any blocking bugs are resolved.

I'm having some trouble reproducing the buggy behavior exactly, though I have found some weird issues with the mouse interface when I play with it. It seems sometimes the gTile window shows up in front of a regular window like Chrome, but it only responds to mouse hovers when the Chrome window is moved so it does not occlude the gTile window.

Is what you're describing a regression or does it occur in the released version?

If you have a convenient way to record the screen during the buggy behavior, that might be easiest to understand.

**Comment by scherepanov** [comment]
I do observe strange behaviour of mouse interface. Just try several times to use mouse interface in a row.
First time it works perfectly fine. I do observe delay in GUI activation on all subsequent times, around 5 seconds. I hover and click mouse, GUI elements are not responcive. After initial delay, it continue to work properly. It happens pretty much every time, except very first.
I do not think it is extremely big deal, but for users who are bound to mouse it can be frustrating.
Apart from this, works fine.
Let me know if you do not observe this behaviour. Gnome recently do show up some buggy GUI behaviour, disappearing after updates. Though, I am on very recent Fedora.
If you do not see this behaviour, I will merge as-is. Will attribute it to bugs in gnome-shell that exist in fedora and already fixed in your distribution. Let me know.

**Comment by scherepanov** [comment]
Checking...

**Comment by scherepanov** [comment]
Abnormal behaviour stays.
Looks like it is a bug in gnome-shell. 
I am watching logs. When gTile GUI not responding, I am hovering mouse pointer over several squares in gTile windows. Then, after around 5 seconds, suddenly a bunch of logs show up, related to hovering over several tiles.
It is clearly something inside gnome-shell.
I am merging.

**Comment by scherepanov** [comment]
BTW you are very welcome to submit more changes.

**Comment by gonzojive** [comment]
I'm playing with the hover and the only strange behavior I can reproduce is that sometimes I'm able to hover over the Grid widget by about 10 pixels and no highlighting occurs.

Otherwise no luck with reproducing the bug.

Thanks for merging.

**Comment by scherepanov** [comment]
I am blaming gnome-shell. I tried hard to fix some GUI bug recently, to no avail. And, with gnome-shell upgrade, it start working just fine.

**Pull request merged**
