### PR TITLE
Reinitialize girds on monitors-changed event (fixes #165)

### LINKED ISSUE #165: gTile crashes when disconnecting one of the monitors
When working on multiple monitors setup and disconnecting/connecting one of the monitors gTile plugin crashes. I've debugged the problem and the logs for the gnome-shell says:
```
JS ERROR: TypeError: grid is undefined
showTiling@/home/crabtree/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:897:29
toggleTiling@/home/crabtree/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:942:9
 _onButtonPress@/home/crabtree/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:541:9
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
```

It seems that the grids collection is not refreshed after the state of the monitors is changed. I've managed to solve the problem by connecting to the event `'monitors-changed'` and re-initializing the girds when it happens.

### PR DESCRIPTION
**Pull request by crabtree**
See #165

### CODE REVIEW

**Comment by scherepanov** [comment]
Nice! I tried it in past, and cannot catch this event.
Can you add one more commit - disconnect this event in disable?
I will be able to test over weekend, will bring second monitor. Will merge after testing.

**Comment by scherepanov** [comment]
Also, may be destroy grids on this event, before initializing again?

**Comment by crabtree** [comment]
Sure I will try to handle the event appropriately. Please test it, as I'm not entirely sure if this is best fix for the problem. It works for my case but I'd say more testing is required on different environments and setups.

**Comment by crabtree** [comment]
The whole problem here is that after monitors-changed event the computed monitor key differs. Consider a setup with one monitor with resolution 1920 and second 3440. According to that we will have monitor 0 with key 0:1920:(y not relevant here) and monitor 1 with key 1920:3440:(y not relevant here). After disconnection the screen 0 we will have only one key 0:3440:(y not relevant here). The destroyGrids function iterates over the monitors and generates the keys based on that. 
In my opinion there should be a change done, the call to initGrids should persist somewhere the recorded monitors and their keys, then destroyGrids should operate on that persisted keys. The event monitors-changed should reinitialize the monitors keys persisted.

**Comment by scherepanov** [comment]
Do it!!!!!

**Comment by crabtree** [comment]
Another option would be to iterate in the destroyGrids not over the monitors but over the existing keys in the grids collection. It may be easier to implement as it requires less code changes.

**Comment by crabtree** [comment]
The destroyGrids is refactored, everything seems to work for me except for one caveat, after the event happens the window with the focus is moved from its desired location. Please test the PR and maybe you will spot another issues.

**Comment by scherepanov** [comment]
Looks very reasonable. Will try to test over weekend, will merge afterwards

**Comment by scherepanov** [comment]
Have not been able to test - just do not have additional monitors.
Will try again on Wednesday.

**Comment by scherepanov** [comment]
Works for me, when I am changing size of screen for remote desktop.
I think it is good enough for merging.

**Pull request merged**
