### PR TITLE
Fixes #67

### LINKED ISSUE #67: Undesired behaviour if mouse happen to be over the gtile interface.
I'm using keyboard shortcuts to place windows with gtile, and when I tap super+enter, I can then use arrow keys or shift and arrow keys to move windows from their current position/size to a new position/size in the grid.

With good muscle memory I can execute the motions I want without thinking because I know where the window is and where I want it to be, so the keypresses I have to make are deterministic.

However, if when I press super+enter, the mouse happens to be on top of the mini-grid, then even if the mouse is not moving, the position of the mouse is used as the starting position for motion and resizing, rather than the current position of the window. 

This throws a spanner in the works for resizing/moving windows with deterministic keystrokes, as I have to look to see whether the mouse is over the mini-grid when it pops up, so I can't mentally "queue up" the keystrokes required to move the window until I check this. I have to press super+enter, wait for my brain to register where the mouse is, then queue up further keystrokes. For me this prevents using gtile from becoming completely internalised in my mind, I am still having to put thought into moving windows rather than it being automatic.

What would completely solve this issue is if the initial position of the mouse were ignored by gtile when the mini-grid pops up, and the mouse position only taken into account if the user moves or clicks the mouse. This would completely solve my problem, and would not interfere with mouse usage as the mouse position would be taken into account as soon as there was any mouse movement or clicking.

### PR DESCRIPTION
**Pull request by scherepanov**
Better calculation of initial window position on a grid, avoiding jumps in size
Some logic cleanup

### CODE REVIEW

**Comment by scherepanov** [comment]
@JMurph2015 can you look on this PR

**Comment by scherepanov** [comment]
Fixed - please take a look again

**Comment by scherepanov** [comment]
Hmmm... It still says "Review required - Merging is blocked".
Probably you need to change "suggested changes" to "approved" on first commit?

Please take a look!

**Comment by StuntsPT** [comment]
Humm... I've tried to approve the changes again, but the 'review' required is still there.
I'm doing this from my phone, I'll take a closer look at it when I have access to one of my boxes agian.

**Comment by scherepanov** [comment]
May be you need to change "Changes suggested" to "approved" on first commit?
No idea what happen.

**Comment by JMurph2015** [comment]
Merged

**Comment by StuntsPT** [comment]
Cool!

**Comment by scherepanov** [comment]
Thanks!
I will try to issue fix for #67, and will release new version into EGO.

**Comment by scherepanov** [comment]
I released new version to EGO. It is around 60 in review queue, can take a while till it will get there.

**Pull request merged**
