### PR TITLE
add option for keyboard shortcuts to target monitor of mouse cursor

### PR DESCRIPTION
**Pull request by mchristiansen**
This PR adds the option to allow preset keyboard accelerator shortcuts to automatically target the monitor where the mouse cursor is currently. Disabled by default to ensure current behavior isn't changed.

### CODE REVIEW

**Comment by scherepanov** [comment]
Looking at your code, do I understand it correctly:
When using preset keyboard shortcut, window will be moved to monitor, where mouse pointer is now?
I cannot check how your PR actually works, I do not have several monitors at home, need to do check at office.

When working with several monitors, I do use gTile in my routine workflow.
This is how I am using gTile:
1)Set focus on window I want to resize/move/move to different monitor. You can use Gnome built-in keyboard shortcuts to set focus to desired window, or you can click on window.
2) activate gTile (you can activate gTile before step 1), I am using keyboard shortcut <Super-Enter>
2)Position/resize window using gTile keyboard shortcuts
3) I am using Gnome built-in keyboard shortcuts <Super-Alt-Arrows> to move window to monitor left/right (or up/down if you have vertically arranged monitors, I have horizontally arranged).
4) Deactivate gTile <ESC>

My workflow is using combination of Gnome built-ins and gTile shortcuts. Not require grabbing mouse in process.

Looks like you are trying to do same, except instead of using Gnome built-in keyboard shortcuts, you want to grab mouse, and move pointer to other monitor (without clicking anywhere)

That is much less handy than keyboard approach. Grabbing and moving mouse in the middle of pressing sequence of key combination is quite inefficient.

Sorry if I incorrectly understand how your PR works. I am raising concerns that you are suggesting workflow that would be inefficient.

I will be able to carefully check new functionality of your PR next week.

**Comment by mchristiansen** [comment]
You're exactly right, it targets the window placement at the monitor of the mouse pointer instead of the monitor of the current window.

I use several monitors regularly (up to 3 when using a laptop) and with this change I use gTile like this:

1) Focus window, usually using Alt+Tab
2) Activate gTile using keyboard shortcut (for me Alt+Shift+A)
3) If mouse is not on the screen I want move mouse to desired monitor
4) Use accelerator keyboard shortcut to resize to desired preset grid placement

This goes in conjunction with my prior PR (#253) for auto-closing the gTile window after a keyboard shortcut is used to resize. This provides the benefit that, for my shortcut setup, I can perform step 3 at the same time I'm doing steps 1 and 2, assuming the gTile activation keybinding and accelerator keybinding are reachable with just my left hand (for me, everything I use regularly is). That means the overall time taken winds up being the same regardless of which monitor I'm targeting without having to hit another shortcut. I do also have a global switch to next monitor keybinding that I set up expecting to use it most of the time so I didn't have to fall back to the mouse, but I've found that I wind up using the mouse pointer pretty much all the time.

I'm coming from a Mac using a similar tool called Divvy and this is the way it behaves (I can't remember if it's a toggle or just the way it behaves by default), but that's how these things have become part of my normal workflow. If it doesn't match up with functionality you think gTile should have that's okay, but I find it really efficient and easy to remember.

**Comment by scherepanov** [comment]
Well, I would consider using a mouse to point to monitor where window to be moved as very unhandy, considering that you have available keyboard shortcut to do same.
Though I do believe that people are "quite different" and there is no single recipe that fits everybody.
Considering that, I will merge your PR.
Code in your PR looks good. I will check that it works on my multi-monitor setup, and will merge immediately as I will see it works.
I am apologizing in advance if testing will take some time. Delay will be only because I have no access to multi-montor setup immediately, and I need to make sure PR actually works. Do not worry if you will see some delays on this PR merge. 

Meantime, may be you can do some more coding for gTile?
For example, you can implement new feature "swap windows". That should not be a lot of coding.
Idea is that you remember what last window had focus, during current activation of gTile GUI. Keyboard shortcut should swap windows position, current focused window and previous focused window.
Suggested implementation would remember window that had previous focus. GUI activation should erase previous window reference. There is already an object that is being created on gTile activation. You can save previous focused window there.
Feature use will be quite intuitive - activate gTile, using keyboard or mouse set focus to first window, then to second window, and with gTile keyboard shortcut swap them.
Let me know if you have some bandwidth to implement it.

**Comment by mchristiansen** [comment]
Thank you! I appreciate you being open to alternative workflows and I hope it does come in handy for others, particularly those coming from a Mac that may have gotten used to the way Divvy works.

My free time is definitely extremely limited so I can't commit to implementing the feature you suggested, but if I wind up with some time over the upcoming holidays I may give it a shot. Also, I have run into issues using the GUI to resize with the mouse. Specifically when I click the grid the first time it sets the first position and I drag the mouse and see the rectangle show up correctly on the GUI and as the larger screen preview, but when I click a second time to trigger the resize if that second click falls over the preview rectangle the click goes "through" the GUI and actually clicks on the window behind it and the resize doesn't happen. I suspect it also has to do with multiple monitors since it seems to only be an issue with the screen the window is on and not with the other screen, which allows the second click no problem. Maybe you can try to verify this behavior too when you have access to multiple monitors? I will look into it more as well if I have time.

**Comment by scherepanov** [comment]
Works as designed. Merged.
Sorry, tests took longer than expected.

**Pull request merged**
