### PR TITLE
Added global auto tiling hotkeys setting.

### LINKED ISSUE #263: Allow auto tile shortcut to be global like with the presets
Hey,
I couldn't find a issue which already asked for that so I thought I will open a new one. I really love the auto tiling and the resize presets shortcuts feature and I use both of them a ton. One thing that bothers me a bit is that I have to bring up gtile to use the auto tiling shortcuts while I am able to use the resize preset shortcuts directly/globally because I activated the "Global resize presets" option.

I think a  "Global auto tiling shortcuts" option would be really handy :).

### PR DESCRIPTION
**Pull request by asteinba**
Closes #263. Feedback appreciated.

Edit: I added the setting with the default value "false" so it doesn't mess up the setup of current users.

### CODE REVIEW

**Comment by asteinba** [comment]
Okay, now after using it in production I recognized weird behavior. When using the global auto tiling shortcuts, gTile messes up the layout. See the following examples:

Using the **global** 3 column auto tiling shortcut does this:



Using the 3 column auto tiling shortcut when the gTile window is active does this (which is the expected):


Any idea what causes this?

**Comment by asteinba** [comment]
> Okay, now after using it in production I recognized weird behavior. When using the global auto tiling shortcuts, gTile messes up the layout. See the following examples:
> 
> Using the **global** 3 column auto tiling shortcut does this: 
> 
> Using the 3 column auto tiling shortcut when the gTile window is active does this (which is the expected): 
> 
> Any idea what causes this?

Ok, found the reason and fixed it :smiley:

**Comment by SkepBrain** [comment]
Just my 2 cents if you & maintainers don't mind:
Haven't tested it but judging from the code it seems like it will make autotile shortcuts global. But the default hotkeys there are just number keys. Does it mean that if I'm not careful (leave those default values) & flip this flag, it will screw the whole row on my keyboard? 🤔 

If that is the case, maybe some warning should be shown if someone tries to do just that?

**Comment by Karolis-Sakavicius** [comment]
Just my 2 cents if you and maintainers don't mind:
Haven't tested it but judging from the code it seems like it adds a setting to treat autotile shortcuts as global ones. But those shortcuts by default are just all number keys. Does it mean that if I'm not careful (leave the default values) & flip this setting, it will essentially rebind my whole keyboard row? 🤔 

If that is the case, I would suggest to add some warning if someone tries to do that.

**Comment by scherepanov** [comment]
That is correct... default binding is all number row, and will rebind it to gTile, making desktop pretty much unusable.
I agree this is highly undesirable.
May be, my implementation of column tiling should be replaced. I am currently using keys 1-0 to specify 1 to 10 columns.
I was thinking on replacing it with 2 keys - autotile with more and less columns.
First, try to approx figure out how many columns, then on more - do with one more column, less - with one less. In range of 1 - 10 columns. We can similarly add 2 keybindings for rows autotiling.
Advantage is use of only 2 keybindings, covering autotile 1 - 10 columns, or rows.
Or, may be add autotiling on current grid. In this mode, all windows will be "gridified", i.e. aligned to existing grid. First pressing will re-align windows to nearest grid lines, allow overlapping. Repeated pressing will re-align windows on current grid without overlapping (if number of tiles is more than Windows, otherwise some overlapping). It can be horizontal and vertical style of gridifying windows, we can cycle between them on repeated invocation of "gridify".
There are huge number of possible autotiling... each will find it's audience.
I was thinking about allow users to write scriplet to define their own tiling. Scriplet can cycle through all windows and do window re-arrange. Sky is the limit what users can do... though it is very involved and require coding scriplets. It can be saved to file with all settings... and distributed together with gTile.
I do agree we need big warning about overwriting a bunch of keyboard keys, to degree that will make desktop unusable. Adding warning is a good idea.

**Comment by asteinba** [comment]
> Just my 2 cents if you and maintainers don't mind: Haven't tested it but judging from the code it seems like it adds a setting to treat autotile shortcuts as global ones. But those shortcuts by default are just all number keys. Does it mean that if I'm not careful (leave the default values) & flip this setting, it will essentially rebind my whole keyboard row? thinking
> 
> If that is the case, I would suggest to add some warning if someone tries to do that.

Good point! Implemented. What do you think?

Peek 2022-01-08 20-03

**Comment by scherepanov** [comment]
Warning is OK. Checking how it works...

**Comment by scherepanov** [comment]
Works fine! Merging....

**Comment by scherepanov** [comment]
@asteinba thanks for contribution!

Do you have some spare time to do some maintenance work on gTile?

Can you convert all logging to use new format
i.e. replace

log("ERROR: gridKey still found in this.gridsByMonitorKey: " + gridKey);

with 

log('ERROR: gridKey still found in this.gridsByMonitorKey:  ${gridKey}');

Also, there is a bad log entry - missing 'this'

gTile Activating GridSettingsButton ${cols}:${rows}

Let me know if you have some time to work on it.

**Comment by asteinba** [comment]
@scherepanov I'm glad I could help (and also glad I have this feature now :D). I'm really short on spare time atm as I'm slowly transitioning from employment to self-employment.

However my workflow heavily relies on gTile and I'm happy top contribute. I will put this on my to do list but don't expect it to be done in the next few days :).

**Comment by scherepanov** [comment]
No hurry! Do it when you will have spare time.

**Comment by scherepanov** [comment]
Do not forget to ask your new employer for a raise!

**Pull request merged**
