### PR TITLE
Preferences Dialog

### PR DESCRIPTION
**Pull request by schnz**
- Implementation of the preferences dialog
- ~Minor fixes in `gnome-shell.d.ts`~
    - The `d.ts` file now imports type references from `@girs/*` npm packages as of the latest commit on master
- Minor improvements to `README.md`
- Adapt GitHub workflow to build a `.zip` archive for distribution on extensions.gnome.org

### CODE REVIEW

**Comment by schnz** [comment]
@scherepanov  If you find time, I would appreciate if you could review this PR. Do you find something else missing that would prevent a submission of the extension on EGO?

**Comment by schnz** [comment]
Great news: We can now use the `@girs/*` npm packages as opposed to the `@gtile/*`  packages that were necessary until now! Just [commited](https://github.com/gTile/gTile/commit/0247d356878cfde4b5514b497b6f4e4dd92dcfe7) the changes on the master branch and rebased this PR accordingly.

**Comment by scherepanov** [comment]
Sorry missed this message.
Will review tomorrow early morning. Will publish to EGO.

**Comment by scherepanov** [comment]
Looks very nice!
Great job @schnz !

**Review by scherepanov — COMMENTED** [review]
Looks nice!

**Comment by scherepanov** [comment]
Bummer. No longer can upload to EGO from office due to tightened security. Will have to wait till tomorrow.
Also, new gTile does not work on my office linux with gnome-shell 42.5 :-( that will makes life slightly harder than it should be.

**Comment by scherepanov** [comment]
Tried to upload tgz file to EGO... as expected, not working.
My laptop is Windows, and used only to remote to Linux. Have not used Windows for ages. Working on Windows feels surreal.
Found some cloud conversion tool tgz -> zip. Seems to be working fine, I have not found any evidence of tampering, though file size grew from 52KB to 83KB.
Now gTile uploaded to EGO, will see how long it will take to approve. New gTile will show up on EGO after it will be approved.

**Comment by schnz** [comment]
@scherepanov you can tag the latest master commit (HEAD) and push.. It will automatically create a release and a zip file that you can upload. Currently not on my notebook, hence I can't create a tag right now.

As with Gnome 42.5: Shouldn't the old gTile continue to work on Gnome 42?

**Comment by scherepanov** [comment]
It is fully expected that gTile re-write will work only on Gnome 45. Of course will be no requests to make new gTile compatible with old Gnome versions. It is a change for me, I used to do some gTile work at office when I had a mood. Now I cannot do coding or upload to EGO form office, all activity restricted to home.
I will try to add new tag on github web, should have same effect.

**Comment by scherepanov** [comment]
Can we have Preferences dialog open on right-click on gTile icon on toolbar?

gTile window opened with mouse pointer in the middle of title bar.
That is departure from previous behavior - gTile was opening in center of focus window.
Opening gTile window in mouse pointer position makes for unpredictable UI on very large screen, when gTile window pop up somewhere in other corner.

Previous behavior - when focus window switched (with Alt-Tab or mouse click etc), gTile window jump to center of new focus window. now it stays in same place. That is little bit less intuitive behavior.

And there is a bug: when mouse pointer is close to lower edge of monitor, gTile window opened with lower border on windows bottom, to be fully visible. If mouse cursor happens to be in grid in gtile window, it is automatically show single tile pointed by mouse. Previous version of gtile contains special code - gTile window opens in center of focus window, but not to contain mouse pointer. That makes for predictable UI with keyboard.

**Comment by scherepanov** [comment]
Bug: gTile window open when there is no window with focus.
To reproduce, you can click on desktop background. Then you can open gTile window with Super-Enter of click on icon. You can do all resizing but it produces no effect on any windows.

**Comment by scherepanov** [comment]
Preferences dialog has title a little bit trimmed from top.
I have clean fresh Ubuntu 23.10 install with latest upgrade, no changes to display settings or font size.

**Comment by schnz** [comment]
> Can we have Preferences dialog open on right-click on gTile icon on toolbar?

I thought about this as well. But the gnome-shell [source code](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/ac7ef665a1eb583a9548edfdd065b8eff8696b30/js/ui/panelMenu.js#L109-113) indicates that panel buttons shall all behave in the same manner, i.e., they should either open an (arbitrarily complex) popup menu or act as a simple [toggle button](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/ac7ef665a1eb583a9548edfdd065b8eff8696b30/js/ui/popupMenu.js#L985-997).  So I would stick with the Gnome conventions here. But we could certainly add a button to the UI which opens the preference dialog, e.g., instead of the button that in the original extension toggled the animation behavior of gTile (and is no longer preset in the rewrite because it reads the animation preferences from the global Gnome settings). The reason I did not do that, was because I was too lazy to add an appropriate image for the new button (a cog wheel). But it would be a simple task.

> gTile window opened with mouse pointer in the middle of title bar. [...]

Yes. I also pointed this out in the [Differences to the original extension](https://github.com/gTile/gTile/pull/341) section of #341. There are two reasons why I decided to take that approach:

1. While I kind of liked the old behavior, the placement of the overlay seemed odd at times, e.g. for very small (thin in width or height) windows, or as you said, when the mouse cursor was in the area where the popup was supposed to be opened. It didn't felt consistent to me.
2. For users that use their mouse to perform window tiling, I find it more intuitive that the overlay opens at the mouse cursor so  I don't have to navigate to the position where the popup opens.

To be fair, the second point is invalid for users which primarily use their keyboard to move and resize windows (<kbd>Arrow</kbd> and <kbd>&lt;Shift&gt;Arrow</kbd> keys). But for users who prefer the mouse I would argue its much more convenient whereas for keyboard users it shouldn't make much of a difference.

That being said: If there is a proposal on how to place the overlay both consistently and intuitively I could see myself adapting this behavior. Of course, you (or anyone else) is also free to implement the old behavior on their own. I wouldn't object on that either, but I also wouldn't invest my own time to change it back due to the reasons I mentioned above.

> And there is a bug: when mouse pointer is close to lower edge of monitor, gTile window opened with lower border on windows bottom, to be fully visible.

Indeed. I would have to think on how to solve this. Maybe it's possible to ignore the mouse when gTile is opened until it's moved for the first time.

> Bug: gTile window open when there is no window with focus.

Interesting. Is that Ubuntu specific? On Arch Linux I can't "unfocus" a window by clicking in the background. If I click on the Desktop, the current focused windows stays in focus. But I also noticed some inconsistencies there. I also liked the behavior of the original extension, that it closed whenever the <kbd>Super</kbd> key was pressed (and opens the Gnome overview). But I wasn't, at the time, able to figure out how to detect that or how the old extension detected that. But yeah, should be fixed.


> Preferences dialog has title a little bit trimmed from top.
Can you show a screenshot of what you mean? It looks like this on Arch:
image

The layout is provided by Adwaita and there aren't any options that I know of to change the layout. So whatever you experience, I am afraid that this is the way that Adwaita want's to display it.

**Comment by scherepanov** [comment]
@schnz 
Yes, all makes sense
I am keyboard-only guy, for me opening gTile window on mouse position is nonsense. While for mouse person opening at mouse makes sense.
We need to add settings where to open gTile window - at mouse position or at window. I will looks at it.
I am sorry for wrong notice, it is not preferences dialog has slightly trimmed title, but gTile window. I will post picture when I will get home.

**Comment by schnz** [comment]
We  could certainly make the opening position of the overlay configurable. Good idea.

As for the "trimmed title". I guess, you refer to what @kamil-karkus also [reported](https://github.com/gTile/gTile/issues/336#issuecomment-1807689853). It  seems like a rendering bug and as far as I can tell this isn't a new bug (regression) - because the UI elements are initialized in the same manner as the original extension did. I couldn't figure out why the font looks odd though. Maybe a CSS issue. Do you have an idea?

**Pull request merged**
