### PR TITLE
Move and resize across grid edges 

### PR DESCRIPTION
**Pull request by extremegf**
This is the prototype I mentioned previously. Edge cases are not handled yet (like changing grid size with Space), but it demonstrates the basic functionality we discussed. 

There are 2 commits. First one is a refactor to keep the logic managable.

I store the corner of and size of a virtual selection, then update them in the switch'es and always redraw at the end. I think this could be robust if edge cases are handled correctly. 

Two questions:

1. Should resize left on, say 1x1 selection at position 2:2, move the 1x1 tile left? Or no-op?
2. Same as above for contract and expand. Should contract lock at 1x1 or expand it?

Do we want to think of this as having two movable pointers to selected area or a rectangle we can resize and move?

### CODE REVIEW

**Comment by scherepanov** [comment]
I think, if you have window height (width) 1, and you are trying to resize left/up and make smaller, it is no-op.
Same for for contract. Contract should lock 1x1.
I think this is more natural behavior.
Though, if you think that moving left/up is more natural, I am OK.
Those are edge cases, and both ways make sense.
It is just a question what looks more natural, and it is very personal perception, with no obvious best way.
You know what I think is more natural behavior. If you think other way is better, I am fine, do it.

**Comment by scherepanov** [comment]
Some new functionality works, but overall buggy. Definitely require more work.

**Comment by extremegf** [comment]
> Some new functionality works, but overall buggy. Definitely require more work.

Yes, this is more of a technical demo and not production ready.

I also think that locking constraction on 1x1 is more natural. Now I'll polish the implementation.

**Comment by extremegf** [comment]
This change:
- properly initiazlies windows size
- handles gride size change
- forgets state after you hide the widget
- supports contract and expand global shortcuts

Let me know what you think.

**Comment by scherepanov** [comment]
Very good job!
Works perfectly well. 
Nice refactor of move implementation!
Feature feels very natural. I do not think it requires any additional explanation in docs, so natural behavior.
Thanks for contribution - merging!

**Comment by scherepanov** [comment]
@extremegf do you have time to fix #233 ?
Gnome-shell extension reviewers will not let me to post new version of gTile without completely removing all references to Lang.
There were 3 places where Lang has been used, I fixed two but one left.
Would you mind looking on it in spare time.

**Comment by extremegf** [comment]
Ok, I'll post a PR removeing Lang.

**Pull request merged**
