### PR TITLE
Custom global accelerators for expanding, contracting and moving active window.

### PR DESCRIPTION
**Pull request by Strauman**
This pull request adds another set of accelerators that can expand and contract the current window from all edges (top, bottom, left and right), as well as move around on the grid.

This is performed by making a set of new hotkeys that are bound at the same time as the presets.
Further more modifications to `keyMoveResizeEvent` in `extensions.js`  had to be done to separate this new functionality from the existing prefix functionality. Specifically a `is_global` flag is added to its parameters, as well as the logic for expanding and contracting the window.

This should perform what is asked in #112.

### CODE REVIEW

**Comment by scherepanov** [comment]
Can you add checkbox in preferences - Global Move/Resize enabled, and have it enabled by default?
When disabled, new functionality will not work.
Also, what do you think about adding Windows7-style tiling functionality by global move/resize keys? That would be enough for some users. Windows7-style tiling can be controlled by additional checkbox in preferences.
I think having separate expand/contract is an overkill, but you can disable some shorcuts and have similar control to what is implemented now, when expand/contract is only for right and lower edges of a window.
That to say, it is way too many shortcuts, and configuring them is not something users are doing.
What do you think about little project - make config/shortcuts save/load from file. gTile can have several config files, like themes, with description what is inside, each provide it's own settings. Users can edit/save/change theme. gTile will come with several preconfigured keyboard shorcuts, for different work style and different keyboard - for laptops or desktop. Let me know if you are interested.

**Comment by Strauman** [comment]
> Can you add checkbox in preferences - Global Move/Resize enabled, and have it enabled by default?

Yes, I'll get right on that :)
> Also, what do you think about adding Windows7-style tiling functionality by global move/resize keys?

Can you elaborate on what you mean when you say Windows 7-style tiling?
> I think having separate expand/contract is an overkill

I use an 40" ultra-wide screen at work, which makes window tiling a very important part of my workflow.  I think that no functionality is redundant as long as the default settings are intuitive, and that that extra functionality is configurable. I love it when apps have "Easy"-mode that configures typical high level things, and an "Advanced"-mode for the more esoteric settings.

> That to say, it is way too many shortcuts, and configuring them is not something users are doing.

It was the first thing I did 😅, but I hear ya! I wouldn't expect users to use all of the functionality of the software, but rather that users has the option of deciding how they want to use the software.

Also, I had this conception that Linux users were in general more interested in customising workflows and adapt software (like gTile) to their needs. Maybe I'm wrong?

> you can disable some shortcuts and have similar control to what is implemented now, when expand/contract is only for right and lower edges of a window.

Yes, but it frustrated me that I couldn't expand in the direction I wanted to. When I "expanded" using the original functionality, it was different as to which edge would contract/expand. I like having the option to configure this.

> What do you think about little project - make config/shortcuts save/load from file. 

That sounds awesome! Also having custom templates one could use when connected to different screens.

I do have limited time, but I guess I could spare an hour here and there to work on this. So if you're up for being patient waiting for me now and again, I'm all onboard 🙂.

**Comment by Strauman** [comment]
I'm a bit confused as to what the exact functionality of window 7-tiling is.
However, with this pull request, moving tiles with global short cuts, and expanding and contracting, should be a piece of cake to make more user friendly and intuitive.

**Comment by scherepanov** [comment]
Cool!
I am patient and will wait whatever time you need.
1) I have pending PR on scherepanov/gTile branch. It contains couple of fixes, and "snap-to-neighbors" functionality. If you can additionally test snap-to-neigbors, would be very nice. Point is that it will be too many changes, and branches may be not able to merge. Can you incorporate those commits into your branch?
2) It is very hard to explain functionality of Windows7 tiling. It is best to install WinTile extension and try. 2x2 is what Windows7 implements (I think, I do not have Windows and cannot deny or confirm this statement).
3) extension.js is way too big. I had a strong desire to break it into several files. May be, you can look into separating all preset definitions into separate file? Also, pretty names can be taken from settings, instead of hardcoding.
And a lot of other things...

**Comment by Strauman** [comment]
1. I'll look into it.
2. Will do! I run windows 10 on virtual box sometimes. I'll play around.
3. Agreed. Also, the code is repetitive and a little messy. I think parts should be rewritten and all of it should be commented. 3. would take a lot of time though.

Also, maybe integrate Travis CI for checking syntax and so forth? Then the code would be more coherent.

**Comment by Strauman** [comment]
Set up gitter for com?

**Comment by scherepanov** [comment]
Glad to her.
Suggestion - let's do "smallish" releases.
I past, there were several attempts to do large code changes, none of them were competed because people are busy and loosing interest in long-running projects.
Let's limit scope of this PR.
Please put my changes from scherepanov/gTile into this PR, I will test/review and merge into master.
Rest of changes will be in next releases. As I mention, I will strongly prefer to have smallish releases, with primary goal - to deliver actual changes to master and not to abandon efforts.
Gitter for com is a nice idea.

**Comment by scherepanov** [comment]
Looks like "global change grid size" is not working.
I assigned '<Ctrl>Space' for global change grid size.
When I am invoking it, logs (journalctl -f" are shoowing that keyCahngeTiling are being called twice. With grids defined as 8x6 and 4x4, it changed twice and return to original settings.
I am checking current grid size by showing gTile window, and grid size is nto changing.
See logs, see double invocation of keyChangeTiling:
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile keyChangeTiling
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile Checking grid settings size 0 have cols 8 and rows 6
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile Checking grid settings size 1 have cols 4 and rows 4
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile found matching grid nbCols 4 nbRows 4 next key is 0
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile New settings will be nbCols 8 nbRows 6
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile refreshGrids
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile New settings are nbCols 8 nbRows 6
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile keyChangeTiling
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile Checking grid settings size 0 have cols 8 and rows 6
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile found matching grid nbCols 8 nbRows 6 next key is 1
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile New settings will be nbCols 4 nbRows 4
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile refreshGrids
Feb 23 12:05:44 supermedia gnome-shell[11627]: gTile New settings are nbCols 4 nbRows 4

**Comment by scherepanov** [comment]
Can you add logging to each invocation of global move/resize, similar to how it is done for other functions?
It will make BY FAR easier to troubleshoot.

**Comment by scherepanov** [comment]
Looks pretty good, I found only one thing that does not work.
Other stuff is smallish things.
What does not work:
Global grid size change is not working. It is being called twice, and on grid sizes 8x6 and 4x4 it cycles through both and return to original.
If you will check on gTile window, grid size really not changing.
Logs:

Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile keyChangeTiling
Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile Checking grid settings size 0 have cols 8 and rows 6
Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile found matching grid nbCols 8 nbRows 6 next key is 1
Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile New settings will be nbCols 4 nbRows 4
Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile refreshGrids
Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile New settings are nbCols 4 nbRows 4
Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile keyChangeTiling
Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile Checking grid settings size 0 have cols 8 and rows 6
Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile Checking grid settings size 1 have cols 4 and rows 4
Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile found matching grid nbCols 4 nbRows 4 next key is 0
Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile New settings will be nbCols 8 nbRows 6
Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile refreshGrids
Feb 23 12:53:52 supermedia gnome-shell[17784]: gTile New settings are nbCols 8 nbRows 6

Apart from this, everything else looks fine.
Now, small cosmetic things.
How do you feel if I will commit directly to your branch? It would be nice if you will do stuff below, but I can do it my myself.

Small things:
1) Please assign default accelerators for global move-resize:
'<Ctrl>Arrows` - global window move
'<Ctrl><Shift>Arrows' - for global right and bottom edges expand and contract
Left and upper edges global shortcut should remain unassigned
That will keep feel similar to what users are used to now.
2)Global grid size change should be unassigned (it is very unobvious behaviour and you cannot see what is current grid size, this option is for users who really want it)
3) Change name in prefs dialog to "Global accelerators for moving and resizing windows". 
4)Global accelerators for move/resize should be disabled by default. There is a concern about polluting global shortcut namespace, causing undesired conflicts with gnome shell and other extensions shortcuts. Users shoudl enable when they really want it.
5) Please add logging for calls to global shortcuts.

And, if you can, please put changes from my branch on top of yours. I fixed bug you noticed.

**Pull request merged**
